services:
  db:
    image: postgres:17.2-alpine3.21
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  app:
    build:
      context: .
    depends_on:
      - db
    restart: on-failure
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    volumes:
      - .:/medods-jwt-auth-sources
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SERVICE_HOST: ${SERVICE_HOST}
      SERVICE_PORT: ${SERVICE_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

volumes:
  pgdata:
